task: 5 # (1 or 5)
task1:
  exp_name: 'test0'
  mode: train #(train or validate)
  epochs: 200
  init_epoch: 0
  num_classes: 10
  batch_size: 64
  lr: 0.00001
  gpu: yes
  save_tensorboard: no
  save_weights: no
  save_weights_freq: 10
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
task5:
  exp_name: 'test_resnet_8'
  mode: train #(train or validate)
  epochs: 5000
  init_epoch: 0
  num_classes: 8
  threshold: 0.6
  model: 'resnet'  # rnn / resnet / baseline
  batch_size: 128
  lr: 0.00001
  gpu: yes
  save_tensorboard: no
  save_weights: no
  save_weights_freq: 10
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
  mixup:
    apply: False
    alfa: 0.5
    rate: 2 # For each real image, rate mixup images

processing:
  task: 5       #(1 or 5)
  mode: validate   #(train or validate)
  deltas: no    #(yes or no)
paths:
  audio: /home/data/audio/
  spectra: /home/data/spectrogram/
  weights: /home/weights/
  tensorboard: /home/tensorboard/
