task: 1
task1:
  nn:
    mode: train
    epochs: !!int 200
    init_epoch: !!int 0
    num_classes: !!int 11
    batch_size: !!int 128
    lr: !!float 0.00001
    gpu: !!bool yes
    save_tensorboard: !!bool no
    load_weights: !!bool no
    save_weights: !!bool no
    save_weights_freq: !!int 10
  paths:
    path_spectra: /home/data/allspect/
    path_audio_train: /home/data/audio/
    path_audio_validate: /home/data/audio/
    path_weights: /home/data/models/test2/epoch_396_.pt
    path_tensorboard: /home/code/tensorboard/test_train/
task5:
  nn:
    mode: train
    epochs: !!int 200
    init_epoch: !!int 0
    num_classes: !!int 8
    batch_size: !!int 128
    lr: !!float 0.00001
    gpu: !!bool yes
    save_tensorboard: !!bool no
    load_weights: !!bool no
    save_weights: !!bool no
    save_weights_freq: !!int 10
  paths:
    path_spectra: /home/data/allspect_task5/
    path_audio_train: /home/data/audio-dev/train/
    path_audio_validate: /home/data/audio-dev/validate/
    path_weights: null
    path_tensorboard: /home/code/tensorboard/test_train/
processing:
  deltas: no
generator:
  mode: train
