testing:
	python main.py config_test
train:
	python main.py config_mfcc
weights:
	python main.py config_no
	python main.py config_yes
mixup:
	python main.py config_rate2
	python main.py config_rate4
	python main.py config_rate6
nmf:
	python main.py config_yes
	python main.py config_no
