testing:
	python main.py config_test
deltas:
	python main.py config_deltas
all:
	python main.py config_all
transfer:
	python main.py config_all23
	python main.py config_mfcc23
	python main.py config_deltas23
	python main.py config_nmf23
mini:
	python main.py config_minideltas
	python main.py config_minimfcc
	python main.py config_mininmf
	python main.py config_miniall
