testing:
	python main.py config_test
deltas:
	python main.py config_deltas
	
train:
	python main.py config_metricheck
	python main.py config_deltas
	python main.py config_mixup2_mfcc
	python main.py config_mixup2_deltas
	python main.py config_mixup2_nmf

weights:
	python main.py config_no
	python main.py config_yes
mixup:
	python main.py config_rate2
	python main.py config_rate4
	python main.py config_rate6
nmf:
	python main.py config_yes
	python main.py config_no
