version: '2.3'

services:

  project1:
    image: dsap
    container_name: DSAP
    working_dir: /home
    build: .
    ipc: host
    volumes:
      - ../code:/home/code
      - ../data:/home/data
      - ../tensorboard:/home/tensorboard
      - ../weights:/home/weights
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONPATH=/home/code
      - DISPLAY=unix$DISPLAY
      - /usr/local/cuda:/usr/local/cuda
    env_file:
      - ../.env
    ports:
     - "8888:8888"
    command: tail /dev/null -f

    depends_on:
        - mongo
    runtime: nvidia
  mongo:
    image: mongo:3.4.1
    container_name: mongod
    ports:
      - 27077:27017
    volumes:
      - ../db:/data/db

  tb:
    image: tensorflow/tensorflow:2.0.0
    container_name: tb
    working_dir: /home/tensorboard
    volumes:
      - ../tensorboard:/home/tensorboard
    command: tail /dev/null -f

    # command: tensorboard --logdir /home/tensorboard
