version: '2.3'

services:

  project1:
    image: dsap
    container_name: DSAP
    working_dir: /home
    build: .
    ipc: host
 
    volumes:
      - ../code:/home/code
      - ../data:/home/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONPATH=/home/code
      - DISPLAY=unix$DISPLAY
      - /usr/local/cuda:/usr/local/cuda
    ports:
      - 6006:6006

    command: tail /dev/null -f

    runtime: nvidia

    depends_on:
        - mongo

  mongo:
    image: mongo:3.4.1
    container_name: mongod
    ports:
      - 27077:27017
    volumes:
      - ../db:/data/db

