task: 5 # (1 or 5)
task1:
  exp_name: 'test0'
  mode: train #(train or validate)
  epochs: 200
  init_epoch: 0
  num_classes: 10
  batch_size: 64
  lr: 0.00001
  gpu: yes
  save_tensorboard: no
  save_weights: no
  save_weights_freq: 10
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
task5:
  exp_name: 'exp.5.8.mixup2.deltas'
  mode: train #(train or validate)
  epochs: 300
  init_epoch: 0
  num_classes: 8
  threshold: 0.5
  model: 'resnet'  # rnn / resnet / baseline
  batch_size: 160
  lr: 0.00001
  gpu: yes
  save_tensorboard: yes
  save_weights: yes
  save_weights_freq: 10
  telegram: yes
  pondweights: yes
  dropout: 0.3
  features: 'deltas'   # 'nmf' or 'mfcc' or 'deltas'
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
  mixup:
    apply: yes
    alfa: 0.5
    rate: 2 # For each real image, rate mixup images

processing:
  task: 5         #(1 or 5)
  mode: train     #(train or validate)
  deltas: yes     #(yes or no)
  features: 'deltas' # 'nmf' or 'mfcc' or 'deltas'
paths:
  audio: /home/data/audio/
  spectra: /home/data/spectrogram/
  deltas: /home/data/deltas/
  nmf: /home/data/activations/
  weights: /home/weights/
  tensorboard: /home/tensorboard/
