task: 5 # (1 or 5)
task1:
  exp_name: resnet
  mode: train #(train or validate)
  epochs: 150
  init_epoch: 0
  num_classes: 10
  batch_size: 64
  lr: 0.0001
  gpu: yes
  model: resnet
  save_tensorboard: yes
  save_weights: yes
  save_weights_freq: 10
  dropout: 0.3
  telegram: yes
  features: mfcc   # 'nmf' or 'mfcc' or 'deltas'
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
  mixup:
    apply: no
    alfa: 0.5
    rate: 0 # For each real image, rate mixup images

task5:
  exp_name: exp.5.8.mini.mfcc
  mode: train #(train or validate)
  epochs: 100
  init_epoch: 0
  num_classes: 8
  threshold: 0.5
  model: resnet  # rnn / resnet / baseline
  batch_size: 16
  lr: 0.00001
  gpu: yes
  save_tensorboard: yes
  save_weights: yes
  save_weights_freq: 10
  telegram: yes
  pondweights: yes
  dropout: 0.5
  features: mfcc   # 'nmf' or 'mfcc' or 'deltas'
  transfer_learning:
    load: no
    exp_task: null  # e.g.: 'task1'
    exp_name: null  # e.g.: 'test0'
    exp_epoch: null # e.g.: 150
  mixup:
    apply: no
    alfa: 0.5
    rate: 0 # For each real image, rate mixup images

processing:
  task: 5         #(1 or 5)
  mode: validate     #(train or validate)
  deltas: no     #(yes or no)
  features: all # 'nmf' or 'mfcc' or 'deltas'
paths:
  audio: /home/data/audio/
  spectra: /home/data/spectrogram/
  all: /home/data/all/
  deltas: /home/data/deltas/
  nmf: /home/data/activations/
  weights: /home/weights/
  tensorboard: /home/tensorboard/
